version: "3"

services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: always

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: always

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/msalena/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/msalena/data/wordpress

