version: '3.9'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #volumes:
    #  - db:/var/lib/mysql
   # ports:
    # - "3306:3306"
    networks:
      - inseption
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    #volumes:
     # - wp:/var/www/html/wordpress
    ports:
      - "9000:9000"
    networks:
      - inseption
    depends_on:
      - mariadb
    links:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    #volumes:
     # - wp:/var/www/html/wordpress
    networks:
      - inseption
    ports:
      - "443:443"
    links:
      - wordpress

networks:
  inseption:
    driver: bridge


volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/msalena/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/msalena/data/wp
