version: '3'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    links:
      - mariadb
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:80"
    links:
      - wordpress


